#!/usr/bin/env bash

set -ou pipefail

if [[ ! -f bootstrap-init ]]; then
	echo "Bootstrap must be run from bootstrappah directory ..."
	exit 1
fi

echo "\nUpdating Project files...\n"
exe git pull origin master
exe git submodule update --init --recursive
exe git submodule update --recursive

exe() { echo "\$ $@" ; "$@" ; }

bootstrap_linux() {
    printf "\nSetting up Linux\n"
    # Add Python repository
    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo apt-get update -qq

	sudo apt-get install -qq \
		curl \
		git \
		vim \
        fzf \
		rsync \
        python3.9 \
		python3-pip \
        ripgrep \
		ssh

    sudo pip3 install virtualenvwrapper -qq

    # Install homebrew for linux
    # /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

bootstrap_mac(){
    info "Setting up Mac"
    exe sh brew.sh
}

case "$OSTYPE" in
  darwin*)
	os='mac'
    bootstrap_linux
    ;;
  *)
	os='nix'
    bootstrap_mac
    ;;
esac

echo "Initialization complete"
