#!/usr/bin/env bash

set -euo pipefail

if [[ ! -f bootstrap ]]; then
	echo "Bootstrap must be run from dotfiles directory ..."
	exit 1
fi

case "$OSTYPE" in
  darwin*)
	os='mac'
    ;;
  *)
	os='nix'
    ;;
esac

exe() { echo "\$ $@" ; "$@" ; }

DOTFILES=$(pwd)

# Is zsh my shell?
current_shell=$(echo $SHELL | grep zsh)

if [[ $? -eq 0 ]]; then
    echo "Not running zsh..."
    exit 1
fi

# Install zsh
sudo apt-get install zsh -y
# Change to zsh 
chsh -s $(which zsh)

# Install unattended oh-my-zsh - https://github.com/ohmyzsh/ohmyzsh#unattended-install
if [[ ! -d $HOME/.oh-my-zsh ]]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
else
    echo "oh-my-zsh already installed"
fi

echo "Completed bootstrapping zsh!"
